name = "BM3D"
uuid = "95fb3b36-088a-43fb-bb1b-b1f34fadbd7d"
authors = ["Longhao.Chen <Longhao.Chen@outlook.com>"]
version = "1.0.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"

[compat]
FFTW = "~1"
ImageCore = "~0.8.21"
Strided = "~1"
julia = "~1"

[extras]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Downloads", "Images", "Statistics", "Test"]
